services:
  static-site:
    image: "."
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`wretched.computer`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.routers.frontend.tls.certresolver=leresolver"
